services:
  moviedatabase:
    image: vlasopoulos/fullstackmoviedatabase:latest
    container_name: moviedatabaserestapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgresmoviedatabase
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    command: >
      -c max_wal_size=4GB
      -c min_wal_size=512MB
    restart: unless-stopped

volumes:
  postgres: